# Generated by Django 3.0.3 on 2020-02-25 21:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
    ]
